# Generated by Django 4.2.7 on 2024-12-05 14:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('profile_picture', models.ImageField(default='default_picture_f.png', upload_to='families/profile_pics/')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('date_created', models.DateField(auto_now_add=True)),
                ('challenge_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge_heads', to=settings.AUTH_USER_MODEL)),
                ('god_father', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Families',
            },
        ),
        migrations.CreateModel(
            name='FamilyBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('E', 'E'), ('D', 'D'), ('C', 'C'), ('B', 'B'), ('B+', 'B+'), ('A', 'A'), ('A+', 'A+'), ('S', 'S'), ('SS', 'SS'), ('SSS', 'SSS')], default='E', max_length=3)),
                ('profile_picture', models.ImageField(default='blank-profile-picture.png', upload_to='players/profile_pics/')),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10)),
                ('bio', models.CharField(blank=True, max_length=60)),
                ('country', models.CharField(choices=[('Cameroon', 'Cameroon'), ('Congo', 'Congo')], max_length=80)),
                ('p_character', models.CharField(choices=[('A (Fourth Raikage)', 'A (Fourth Raikage)'), ('A (Third Raikage)', 'A (Third Raikage)'), ('Akaboshi', 'Akaboshi'), ('Akamaru', 'Akamaru'), ('Akita Inuzuka', 'Akita Inuzuka'), ('Amachi', 'Amachi'), ('Ameno', 'Ameno'), ('Ameyuki', 'Ameyuki'), ('Ameyuri Ringo', 'Ameyuri Ringo'), ('Aniki (missing-nin)', 'Aniki (missing-nin)'), ('Anko Mitarashi', 'Anko Mitarashi'), ('Ao', 'Ao'), ('Asuma Sarutobi', 'Asuma Sarutobi'), ('Asura Ōtsutsuki', 'Asura Ōtsutsuki'), ('Azure Fang', 'Azure Fang'), ('Benga', 'Benga'), ('Benten', 'Benten'), ('Blue B', 'Blue B'), ('Boar-Masked Anbu Member', 'Boar-Masked Anbu Member'), ('Boro', 'Boro'), ('Boruto Uzumaki', 'Boruto Uzumaki'), ('Breeze Dancer', 'Breeze Dancer'), ('Buntan Kurosuki', 'Buntan Kurosuki'), ('Burami', 'Burami'), ('Chiriku', 'Chiriku'), ('Chiyo', 'Chiyo'), ('Chōbee Akimichi', 'Chōbee Akimichi'), ('Chōji Akimichi', 'Chōji Akimichi'), ('Chōjūrō', 'Chōjūrō'), ('Chōmei', 'Chōmei'), ('Chōza Akimichi', 'Chōza Akimichi'), ('Chūkichi', 'Chūkichi'), ('Chūshin', 'Chūshin'), ('Code', 'Code'), ('Conch King', 'Conch King'), ('Condor', 'Condor'), ('Crimson Fist', 'Crimson Fist'), ('Danzō Shimura', 'Danzō Shimura'), ('Darui', 'Darui'), ('Deepa', 'Deepa'), ('Deidara', 'Deidara'), ('Denki Kaminarimon', 'Denki Kaminarimon'), ('Dodai', 'Dodai'), ('Dōshin', 'Dōshin'), ('Dōshu Goetsu', 'Dōshu Goetsu'), ('Eagle-Masked Anbu Member', 'Eagle-Masked Anbu Member'), ('Enko Onikuma', 'Enko Onikuma'), ('Ensui Nara', 'Ensui Nara'), ('Enzo Tenrō', 'Enzo Tenrō'), ('Fudō', 'Fudō'), ('Fuen', 'Fuen'), ('Fuguki Suikazan', 'Fuguki Suikazan'), ('Fukasaku', 'Fukasaku'), ('Funamushi', 'Funamushi'), ('Fū Yamanaka', 'Fū Yamanaka'), ('Gaara', 'Gaara'), ('Gamabunta', 'Gamabunta'), ('Gamakichi', 'Gamakichi'), ('Gamamaru', 'Gamamaru'), ('Gamariki', 'Gamariki'), ('Gamatatsu', 'Gamatatsu'), ('Gengo', 'Gengo'), ('Gennō', 'Gennō'), ('Genshō Ryūdōin', 'Genshō Ryūdōin'), ('Gensui Amagiri', 'Gensui Amagiri'), ('Gitai', 'Gitai'), ('Gozu', 'Gozu'), ('Hagoromo Ōtsutsuki', 'Hagoromo Ōtsutsuki'), ('Hako Kuroi', 'Hako Kuroi'), ('Haku', 'Haku'), ('Hamura Ōtsutsuki', 'Hamura Ōtsutsuki'), ('Han', 'Han'), ('Hana Kaka', 'Hana Kaka'), ('Hanzō', 'Hanzō'), ('Hashirama Senju', 'Hashirama Senju'), ('Hayate Gekkō', 'Hayate Gekkō'), ('Hidari', 'Hidari'), ('Hinata Hyūga', 'Hinata Hyūga'), ('Hiruzen Sarutobi', 'Hiruzen Sarutobi'), ('Hisame', 'Hisame'), ('Hōichi', 'Hōichi'), ('Hōki (Watari)', 'Hōki (Watari)'), ('Hōki Taketori', 'Hōki Taketori'), ('Ibiki Morino', 'Ibiki Morino'), ('Ichi', 'Ichi'), ('Indra Ōtsutsuki', 'Indra Ōtsutsuki'), ('Ino Yamanaka', 'Ino Yamanaka'), ('Inoichi Yamanaka', 'Inoichi Yamanaka'), ('Inojin Yamanaka', 'Inojin Yamanaka'), ('Iruka Umino', 'Iruka Umino'), ('Isobu', 'Isobu'), ('Isshiki Ōtsutsuki', 'Isshiki Ōtsutsuki'), ('Itachi Uchiha', 'Itachi Uchiha'), ('Iwabee Yuino', 'Iwabee Yuino'), ('Izumo Kamizuki', 'Izumo Kamizuki'), ('Jibachi', 'Jibachi'), ('Jiga', 'Jiga'), ('Jiraiya', 'Jiraiya'), ('Jūgo', 'Jūgo'), ('Kabuto Yakushi', 'Kabuto Yakushi'), ('Kagerō', 'Kagerō'), ('Kagura (game)', 'Kagura (game)'), ('Kaguya Ōtsutsuki', 'Kaguya Ōtsutsuki'), ('Kajika', 'Kajika'), ('Kakashi Hatake', 'Kakashi Hatake'), ('Kakō', 'Kakō'), ('Kandachi', 'Kandachi'), ('Kankurō', 'Kankurō'), ('Karin', 'Karin'), ('Karyū', 'Karyū'), ('Katsuyu', 'Katsuyu'), ('Kawaki', 'Kawaki'), ('Kazuma', 'Kazuma'), ('Kiba Inuzuka', 'Kiba Inuzuka'), ('Kido Tsumiki', 'Kido Tsumiki'), ('Kigiri', 'Kigiri'), ('Kiiro', 'Kiiro'), ('Kikunojō', 'Kikunojō'), ('Killer B', 'Killer B'), ('Kirisame', 'Kirisame'), ('Kisame Hoshigaki', 'Kisame Hoshigaki'), ('Kiseru Gankubi', 'Kiseru Gankubi'), ('Kohan Yamanaka', 'Kohan Yamanaka'), ('Koji Kashin', 'Koji Kashin'), ('Kokuō', 'Kokuō'), ('Komachi', 'Komachi'), ('Konan', 'Konan'), ('Konohamaru Sarutobi', 'Konohamaru Sarutobi'), ('Kosuke Maruboshi', 'Kosuke Maruboshi'), ('Kotetsu Hagane', 'Kotetsu Hagane'), ('Kujaku', 'Kujaku'), ('Kurobachi', 'Kurobachi'), ('Kurobane', 'Kurobane'), ('Kurotsuchi', 'Kurotsuchi'), ('Kushimaru Kuriarare', 'Kushimaru Kuriarare'), ('Kū', 'Kū'), ('Madara Uchiha', 'Madara Uchiha'), ('Maki', 'Maki'), ('Malice', 'Malice'), ('Mangetsu Hōzuki', 'Mangetsu Hōzuki'), ('Menma (anime)', 'Menma (anime)'), ('Menma Uzumaki', 'Menma Uzumaki'), ('Midnight Blade', 'Midnight Blade'), ('Mifune', 'Mifune'), ('Might Guy', 'Might Guy'), ('Minato Namikaze', 'Minato Namikaze'), ('Mirai Sarutobi', 'Mirai Sarutobi'), ('Mitsuki', 'Mitsuki'), ('Mizuki', 'Mizuki'), ('Monju', 'Monju'), ('Monzaemon Chikamatsu', 'Monzaemon Chikamatsu'), ('Mubi', 'Mubi'), ('Mugino', 'Mugino'), ('Mui', 'Mui'), ('Mukade (movie)', 'Mukade (movie)'), ('Mukai Kohinata', 'Mukai Kohinata'), ('Muku', 'Muku'), ('Murasame', 'Murasame'), ('Muyami', 'Muyami'), ('Mū', 'Mū'), ('Nadare Rōga', 'Nadare Rōga'), ('Nagare', 'Nagare'), ('Namida Suzumeno', 'Namida Suzumeno'), ('Nangō', 'Nangō'), ('Naruto Uzumaki', 'Naruto Uzumaki'), ('Nine-Tailed Naruto Clone', 'Nine-Tailed Naruto Clone'), ('Nurari', 'Nurari'), ('Obito Uchiha', 'Obito Uchiha'), ('Omoi', 'Omoi'), ('Orochimaru', 'Orochimaru'), ('Raiga Kurosuki', 'Raiga Kurosuki'), ('Ranke', 'Ranke'), ('Rasa', 'Rasa'), ('Renga Kokubō', 'Renga Kokubō'), ('Rock Lee', 'Rock Lee'), ('Ruiga', 'Ruiga'), ('Ryuka Tenrō', 'Ryuka Tenrō'), ('Ryōgi', 'Ryōgi'), ('Sadai', 'Sadai'), ('Sai', 'Sai'), ('Saiken', 'Saiken'), ('Sakura Haruno', 'Sakura Haruno'), ('Sana', 'Sana'), ('Sarada Uchiha', 'Sarada Uchiha'), ('Sasori', 'Sasori'), ('Sasuke Uchiha', 'Sasuke Uchiha'), ('Saya', 'Saya'), ('Scarlet Blaze', 'Scarlet Blaze'), ('Seimei', 'Seimei'), ('Sekiei', 'Sekiei'), ('Sekiei (spectator)', 'Sekiei (spectator)'), ('Setsuna', 'Setsuna'), ('Shamo', 'Shamo'), ('Shibuki', 'Shibuki'), ('Shikadai Nara', 'Shikadai Nara'), ('Shikamaru Nara', 'Shikamaru Nara'), ('Shima', 'Shima'), ('Shinki', 'Shinki'), ('Shino Aburame', 'Shino Aburame'), ('Shion', 'Shion'), ('Shiranami', 'Shiranami'), ('Shishio', 'Shishio'), ('Shisui Uchiha', 'Shisui Uchiha'), ('Shitō Akimichi', 'Shitō Akimichi'), ('Shizuku', 'Shizuku'), ('Shizuma Hoshigaki', 'Shizuma Hoshigaki'), ('Shizune', 'Shizune'), ('Shojoji', 'Shojoji'), ('Shukaku', 'Shukaku'), ('Son Gokū', 'Son Gokū'), ('Sora', 'Sora'), ('Suien', 'Suien'), ('Suigetsu Hōzuki', 'Suigetsu Hōzuki'), ('Suika', 'Suika'), ('Suiren', 'Suiren'), ('Suzumebachi', 'Suzumebachi'), ('Taisa Amagiri', 'Taisa Amagiri'), ('Tatewaki', 'Tatewaki'), ('Tayuya', 'Tayuya'), ('Temari', 'Temari'), ('Ten-Tails', 'Ten-Tails'), ('Tenma Funato', 'Tenma Funato'), ('Tenten', 'Tenten'), ('Third Kazekage', 'Third Kazekage'), ('Tobirama Senju', 'Tobirama Senju'), ('Toneri Ōtsutsuki', 'Toneri Ōtsutsuki'), ('Torune Aburame', 'Torune Aburame'), ('Towa', 'Towa'), ('Tsubaki Kurogane', 'Tsubaki Kurogane'), ('Tsukino', 'Tsukino'), ('Tsukiyo', 'Tsukiyo'), ('Tsume Inuzuka', 'Tsume Inuzuka'), ('Tsunade', 'Tsunade'), ('Tsuru Itoi', 'Tsuru Itoi'), ('Urashiki Ōtsutsuki', 'Urashiki Ōtsutsuki'), ('Utakata', 'Utakata'), ('Victor', 'Victor'), ('White Zetsu', 'White Zetsu'), ('Yagura Karatachi', 'Yagura Karatachi'), ('Yamato', 'Yamato'), ('Yome', 'Yome'), ('Yomito Hirasaka', 'Yomito Hirasaka'), ('Yurinojō', 'Yurinojō'), ('Yūgao Uzuki', 'Yūgao Uzuki'), ('Zabuza Momochi', 'Zabuza Momochi'), ('Zō', 'Zō'), ('Ōga', 'Ōga')], default='A (Fourth Raikage)', max_length=30)),
                ('authorized_to_fight', models.BooleanField(blank=True, default=False)),
                ('can_create_family', models.BooleanField(blank=True, default=False)),
                ('language', models.CharField(default='en', max_length=20)),
                ('battle_points', models.IntegerField(default=1000)),
                ('progression', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('referall_code', models.CharField(max_length=80)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefreeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fairness', models.IntegerField(default=1)),
                ('communication', models.IntegerField(default=1)),
                ('timeliness', models.IntegerField(default=1)),
                ('overall', models.IntegerField(default=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(max_length=30)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.family')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.player')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_notifications', to='users.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.badge')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
            options={
                'unique_together': {('player', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.achievement')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
            options={
                'unique_together': {('player', 'achievement')},
            },
        ),
        migrations.AddField(
            model_name='player',
            name='achievements',
            field=models.ManyToManyField(through='users.PlayerAchievement', to='users.achievement'),
        ),
        migrations.AddField(
            model_name='player',
            name='badges',
            field=models.ManyToManyField(through='users.PlayerBadge', to='users.badge'),
        ),
        migrations.AddField(
            model_name='player',
            name='family',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.family'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PasswordRecoveryCode',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
        ),
    ]
