# Generated by Django 4.2.7 on 2024-06-21 12:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8e361801-4ff2-4793-b402-053734eaec62'), primary_key=True, serialize=False),
        ),
    ]
