# Generated by Django 4.2.7 on 2024-12-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(default='477723.jpg', upload_to='players/profile_pics/'),
        ),
    ]
