# Generated by Django 4.2.7 on 2024-12-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_player_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='players/profile_pics/'),
        ),
    ]
