# Generated by Django 4.2.7 on 2024-06-21 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='bio',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8edc1e66-5792-4b7c-97db-5f5df97066e7'), primary_key=True, serialize=False),
        ),
    ]
