# Generated by Django 4.2.7 on 2024-06-21 12:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_family_bio_alter_family_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='can_create_family',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('df623abc-c0de-413e-8f55-1908cd4ac6ff'), primary_key=True, serialize=False),
        ),
    ]
