# Generated by Django 4.2.7 on 2024-06-21 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_player_can_create_family_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d4275fdf-85ee-4733-bbc8-7a94ae550af3'), primary_key=True, serialize=False),
        ),
    ]
