# Generated by Django 4.2.7 on 2024-12-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_playerdefaultimage_alter_player_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(default='/static/images/profile_pictures/6.png', upload_to='players/profile_pics/'),
        ),
    ]
