# Generated by Django 4.2.7 on 2024-06-22 07:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_family_id_alter_player_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1c53f649-d32b-4298-a45e-311356f5d144'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='family',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.family'),
        ),
    ]
