# Generated by Django 4.2.7 on 2024-06-22 18:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_family_id_alter_player_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cd0e4b36-edac-40cb-bee9-7349ff399a50'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PlayerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('invite', 'invite'), ('request', 'request')], max_length=30)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('expiration', models.DateTimeField(blank=True)),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.family')),
                ('sender', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.player')),
                ('target', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_notifications', to='users.player')),
            ],
        ),
    ]
