# Generated by Django 4.2.7 on 2025-04-15 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_date_joined_player_date_points_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('challenge_head', 'challenge_head'), ('casual', 'casual'), ('fighter', 'fighter')], default='casual', max_length=50)),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.family')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
            options={
                'unique_together': {('player', 'family')},
            },
        ),
        migrations.AddField(
            model_name='family',
            name='members',
            field=models.ManyToManyField(related_name='members', through='users.FamilyMember', to='users.player'),
        ),
    ]
