# Generated by Django 4.2.7 on 2024-06-22 19:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_family_id_playernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('27479c4c-4a0e-425d-b073-143b73d1dc7e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playernotification',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
