# Generated by Django 4.2.7 on 2025-04-15 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_familymember_family_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='familymember',
            name='role',
            field=models.CharField(choices=[('challenge_head', 'challenge_head'), ('recruiter', 'recruiter'), ('casual', 'casual'), ('fighter', 'fighter')], default='casual', max_length=50),
        ),
        migrations.CreateModel(
            name='PlayerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
            options={
                'unique_together': {('player', 'event')},
            },
        ),
        migrations.AddField(
            model_name='player',
            name='events',
            field=models.ManyToManyField(through='users.PlayerEvent', to='users.event'),
        ),
    ]
