# Generated by Django 4.2.7 on 2024-06-22 19:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_family_id_alter_playernotification_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9f175c05-6dc9-45e5-b557-54f910c52445'), primary_key=True, serialize=False),
        ),
    ]
