# Generated by Django 4.2.7 on 2024-06-22 19:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a7b973bc-cc9e-425e-8697-61fd438c75ba'), primary_key=True, serialize=False),
        ),
    ]
