# Generated by Django 4.2.7 on 2025-04-28 00:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_event_alter_familymember_role_playerevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
