# Generated by Django 4.2.16 on 2025-05-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_family_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rp_credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
