# Generated by Django 4.2.7 on 2024-06-23 00:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d8ad9915-4316-433c-b0eb-abf279459ce5'), primary_key=True, serialize=False),
        ),
    ]
