# Generated by Django 4.2.16 on 2025-05-31 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_family_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='godfather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.player'),
        ),
    ]
