# Generated by Django 4.2.7 on 2024-06-26 18:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e50bc93a-56fb-46f9-a5e2-49f033b04042'), primary_key=True, serialize=False),
        ),
    ]
