# Generated by Django 4.2.20 on 2025-07-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_player_godfather'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ip_adress',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
