# Generated by Django 4.2.7 on 2024-06-26 18:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a7fca78f-6b84-4c2d-8cae-c47a2522d703'), primary_key=True, serialize=False),
        ),
    ]
