# Generated by Django 4.2.20 on 2025-12-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_player_ip_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='duel_character',
            field=models.JSONField(blank=True, default=''),
        ),
    ]
