# Generated by Django 4.2.7 on 2024-06-27 21:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6810e063-e253-40ec-ad26-4f0921084154'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='can_create_family',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
