# Generated by Django 4.2.7 on 2024-06-28 07:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_family_id_alter_player_can_create_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d28870bd-d62a-45c5-97d6-f511b37de94a'), primary_key=True, serialize=False),
        ),
    ]
