# Generated by Django 4.2.7 on 2024-06-28 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8113597f-0c3b-4d06-a6b6-a7f47c1dea4f'), primary_key=True, serialize=False),
        ),
    ]
