# Generated by Django 4.2.7 on 2024-07-01 13:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_family_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playernotification',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('55b69474-90ef-469a-8bdb-804cdb50dfec'), primary_key=True, serialize=False),
        ),
    ]
