# Generated by Django 4.2.7 on 2024-07-04 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8b67c40b-9c55-4098-89cd-28f375ffe2b3'), primary_key=True, serialize=False),
        ),
    ]
