# Generated by Django 4.2.7 on 2024-07-04 19:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d12315f3-8b44-4db1-8223-576def46a80d'), primary_key=True, serialize=False),
        ),
    ]
