# Generated by Django 4.2.7 on 2024-07-05 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0dc65a78-5550-4d86-803d-ce73f3b729d7'), primary_key=True, serialize=False),
        ),
    ]
