# Generated by Django 4.2.7 on 2024-07-05 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c686160f-2e20-4be1-85fc-8fec7ec5b6cf'), primary_key=True, serialize=False),
        ),
    ]
