# Generated by Django 4.2.7 on 2024-07-05 12:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7259a2ac-d1f9-4863-a30a-49c4fe685883'), primary_key=True, serialize=False),
        ),
    ]
