# Generated by Django 4.2.7 on 2024-07-05 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e9a01e3a-1ea3-457f-bfda-1a09693490b4'), primary_key=True, serialize=False),
        ),
    ]
