# Generated by Django 4.2.7 on 2024-07-05 19:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_player_language_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('326bff6c-be44-4880-80bd-165ac6103b53'), primary_key=True, serialize=False),
        ),
    ]
