# Generated by Django 4.2.7 on 2024-07-05 23:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('41d324d3-a8f0-4cb4-8231-37d28e2f7c7e'), primary_key=True, serialize=False),
        ),
    ]
