# Generated by Django 4.2.7 on 2024-07-07 05:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9582208d-25ea-40a0-9e72-bd9c08c86d54'), primary_key=True, serialize=False),
        ),
    ]
