# Generated by Django 4.2.7 on 2024-07-08 18:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_family_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='battle_points',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='player',
            name='flags',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f8c3a523-e6b0-40ca-ae56-2f956d4c5c5a'), primary_key=True, serialize=False),
        ),
    ]
