# Generated by Django 4.2.7 on 2024-07-10 08:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_player_battle_points_player_flags_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b4e07630-3eca-4975-81db-4751cc97a3d9'), primary_key=True, serialize=False),
        ),
    ]
