# Generated by Django 4.2.7 on 2024-07-11 13:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_family_id_alter_player_p_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6b7bede9-aa2a-4582-b3a3-c00ad0f9ccfa'), primary_key=True, serialize=False),
        ),
    ]
