# Generated by Django 4.2.7 on 2024-07-11 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('280e1254-50a2-4e15-b5e1-05974a037500'), primary_key=True, serialize=False),
        ),
    ]
