# Generated by Django 4.2.7 on 2024-07-11 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6aa64c0f-4b8f-4bc8-b58d-c94ddef71f02'), primary_key=True, serialize=False),
        ),
    ]
