# Generated by Django 4.2.7 on 2024-07-11 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('042d09b8-1bfa-4286-8a88-45276c3c2a37'), primary_key=True, serialize=False),
        ),
    ]
