# Generated by Django 4.2.7 on 2024-07-11 20:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b77a14f7-e15c-4c86-b4a6-09ce1eef0222'), primary_key=True, serialize=False),
        ),
    ]
