# Generated by Django 4.2.7 on 2024-07-11 21:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1734bb55-4e66-4900-80d4-006f61472e99'), primary_key=True, serialize=False),
        ),
    ]
