# Generated by Django 4.2.7 on 2024-07-11 21:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('38b21079-67cd-4c7d-97dd-7d7db8891314'), primary_key=True, serialize=False),
        ),
    ]
