# Generated by Django 4.2.7 on 2024-07-12 13:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ac7b924c-2ce1-4653-88a7-98b64b67e85c'), primary_key=True, serialize=False),
        ),
    ]
