# Generated by Django 4.2.7 on 2024-07-12 13:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2bb32f5e-4745-4e68-a9da-4aab6ecc72c8'), primary_key=True, serialize=False),
        ),
    ]
