# Generated by Django 4.2.7 on 2024-07-12 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('764ee0c9-0b82-4978-9b1e-9f583aa18b6d'), primary_key=True, serialize=False),
        ),
    ]
