# Generated by Django 4.2.7 on 2024-07-13 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('33da5bfd-2ae9-4c8a-8fb8-bf8f98eeffa0'), primary_key=True, serialize=False),
        ),
    ]
