# Generated by Django 4.2.7 on 2024-07-13 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3805a1de-f9b5-4b15-8075-58cbdde3d28c'), primary_key=True, serialize=False),
        ),
    ]
