# Generated by Django 4.2.7 on 2024-07-13 18:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('98a91051-81b7-494c-91ba-fb1bfc9b88ba'), primary_key=True, serialize=False),
        ),
    ]
