# Generated by Django 4.2.7 on 2024-07-14 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_alter_family_id_playerstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('73a596a2-c058-4ce8-90e9-d4a7a8038049'), primary_key=True, serialize=False),
        ),
    ]
