# Generated by Django 4.2.7 on 2024-07-18 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_alter_family_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='pseudo',
        ),
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('66d17d3d-88d5-47e5-ae92-82863edfdc9a'), primary_key=True, serialize=False),
        ),
    ]
