# Generated by Django 4.2.7 on 2024-07-18 12:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_remove_player_pseudo_player_gender_alter_family_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c30c7422-9350-49fe-a186-6b83edc522ca'), primary_key=True, serialize=False),
        ),
    ]
