# Generated by Django 4.2.7 on 2024-07-19 12:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_alter_family_id_alter_player_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2b7f1809-2c3e-45b8-b8d7-41ddd6d710fa'), primary_key=True, serialize=False),
        ),
    ]
