# Generated by Django 4.2.7 on 2024-07-19 18:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a9277ed3-9656-45a7-91b5-487873a1bde1'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playernotification',
            name='notif_type',
            field=models.CharField(choices=[('invite', 'invite'), ('request', 'request'), ('private_message', 'private_message'), ('textpad', 'textpad'), ('family_message', 'family_message')], max_length=30),
        ),
    ]
