# Generated by Django 4.2.7 on 2024-07-20 19:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dabc316e-9479-4540-9d8c-6a816f6b3091'), primary_key=True, serialize=False),
        ),
    ]
