# Generated by Django 4.2.7 on 2024-07-22 13:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_alter_family_id_alter_playernotification_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a871435f-611a-4a87-83b0-485ce9158cee'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
