# Generated by Django 4.2.7 on 2024-07-23 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_alter_family_id_alter_player_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='profile_picture',
            field=models.ImageField(default='default_picture_f.png', upload_to='families/profile_pics/'),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4a3a9fc9-586a-4c7c-919f-5b7f6b291ac1'), primary_key=True, serialize=False),
        ),
    ]
