# Generated by Django 4.2.7 on 2024-07-24 12:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_alter_family_id_alter_playernotification_notif_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='bio',
        ),
        migrations.AddField(
            model_name='family',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('36079ce0-dcae-42da-a2fb-c14b7891ca05'), primary_key=True, serialize=False),
        ),
    ]
