# Generated by Django 4.2.7 on 2024-07-25 23:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_alter_family_id_alter_playernotification_notif_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1522b00f-c1fb-41cf-9aaa-f601af1d3051'), primary_key=True, serialize=False),
        ),
    ]
