# Generated by Django 4.2.7 on 2024-07-30 21:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a72949a3-6f1d-4241-bbf3-a2e3e7fe0bfd'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playernotification',
            name='notif_type',
            field=models.CharField(choices=[('invite', 'invite'), ('request', 'request'), ('private_message', 'private_message'), ('new_textpad', 'new_textpad'), ('family_message', 'family_message'), ('refused_request', 'refused_request'), ('denied_invite', 'denied_invite'), ('battle_accepted', 'battle_accepted'), ('refree_proposal', 'refree_proposal'), ('textpad_accepted', 'textpad_accepted'), ('textpad_refused', 'textpad_refused')], max_length=30),
        ),
    ]
