# Generated by Django 4.2.7 on 2024-08-02 17:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_alter_family_id_alter_playernotification_notif_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5ab0490a-eb7c-481f-9186-b4a726bf92f5'), primary_key=True, serialize=False),
        ),
    ]
