# Generated by Django 4.2.7 on 2024-08-03 23:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0077_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('be72aee4-f1ed-4933-9073-53972831913e'), primary_key=True, serialize=False),
        ),
    ]
