# Generated by Django 4.2.7 on 2024-08-17 10:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bda6dcad-bdc5-4a8d-8579-8564ff55e6f6'), primary_key=True, serialize=False),
        ),
    ]
