# Generated by Django 4.2.7 on 2024-08-17 21:09

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0079_alter_family_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='progression',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a876099e-ca64-494c-a743-f46396c73247'), primary_key=True, serialize=False),
        ),
    ]
