# Generated by Django 4.2.7 on 2024-08-26 12:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_alter_family_id_refreestat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('36ff3c0b-026c-4c9f-8499-155478e29448'), primary_key=True, serialize=False),
        ),
    ]
