# Generated by Django 4.2.7 on 2024-08-28 00:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('69b9c467-4c52-4216-9326-6853e23d23c8'), primary_key=True, serialize=False),
        ),
    ]
