# Generated by Django 4.2.7 on 2024-08-31 08:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0087_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f2dbd661-e3f7-4e5a-95cd-aa6e886a89de'), primary_key=True, serialize=False),
        ),
    ]
