# Generated by Django 4.2.7 on 2024-09-07 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0088_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7a3b6727-d20d-444a-be8e-a630b24f573a'), primary_key=True, serialize=False),
        ),
    ]
