# Generated by Django 4.2.7 on 2024-09-07 14:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0089_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c3a658a0-5b1e-4e90-80c3-36da8bd5ee6d'), primary_key=True, serialize=False),
        ),
    ]
