# Generated by Django 4.2.7 on 2024-09-07 23:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0090_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e8d0ca77-1758-4137-ac83-297ba1f41e8f'), primary_key=True, serialize=False),
        ),
    ]
