# Generated by Django 4.2.7 on 2024-09-07 23:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0091_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6cdd4db3-38ec-416a-8e72-5dfe2f282d83'), primary_key=True, serialize=False),
        ),
    ]
