# Generated by Django 4.2.7 on 2024-09-08 08:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0092_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ffca27a7-3e59-4193-bc38-4da7a4563f38'), primary_key=True, serialize=False),
        ),
    ]
