# Generated by Django 4.2.7 on 2024-09-09 17:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0095_rename_value_badge_title_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6a2bdf12-c52e-4146-ad61-269c8bd5c555'), primary_key=True, serialize=False),
        ),
    ]
