# Generated by Django 4.2.7 on 2024-09-09 17:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0096_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('05d5ae39-6595-4aa5-a627-e7ce6e6bf6b8'), primary_key=True, serialize=False),
        ),
    ]
