# Generated by Django 4.2.7 on 2024-09-12 10:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0097_alter_family_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playernotification',
            name='battle_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5b3140d9-a433-43ce-92c5-fb8fe456e0bc'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playernotification',
            name='notif_type',
            field=models.CharField(choices=[('invite', 'invite'), ('request', 'request'), ('private_message', 'private_message'), ('new_textpad', 'new_textpad'), ('family_message', 'family_message'), ('refused_request', 'refused_request'), ('denied_invite', 'denied_invite'), ('battle_accepted', 'battle_accepted'), ('refree_proposal', 'refree_proposal'), ('textpad_accepted', 'textpad_accepted'), ('textpad_refused', 'textpad_refused'), ('battle_started', 'battle_started')], max_length=30),
        ),
    ]
