# Generated by Django 4.2.7 on 2024-09-12 10:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0098_playernotification_battle_id_alter_family_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f1efc691-670e-4692-9357-e49ee4a71466'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playernotification',
            name='battle_id',
            field=models.UUIDField(blank=True),
        ),
    ]
