# Generated by Django 4.2.7 on 2024-09-12 10:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0099_alter_family_id_alter_playernotification_battle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('37095fdb-aee9-4ca1-b9c2-4d452ec519de'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playernotification',
            name='battle_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
