# Generated by Django 4.2.7 on 2024-09-12 10:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0100_alter_family_id_alter_playernotification_battle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1162b81f-e27a-483b-815c-b9051c25074f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playernotification',
            name='notif_type',
            field=models.CharField(choices=[('invite', 'invite'), ('request', 'request'), ('private_message', 'private_message'), ('new_textpad', 'new_textpad'), ('family_message', 'family_message'), ('refused_request', 'refused_request'), ('denied_invite', 'denied_invite'), ('battle_accepted', 'battle_accepted'), ('refree_proposal', 'refree_proposal'), ('textpad_accepted', 'textpad_accepted'), ('textpad_refused', 'textpad_refused'), ('battle_started', 'battle_started'), ('family_points', 'family_points')], max_length=30),
        ),
        migrations.AlterField(
            model_name='playernotification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.player'),
        ),
        migrations.AlterField(
            model_name='playernotification',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_notifications', to='users.player'),
        ),
    ]
