# Generated by Django 4.2.7 on 2024-09-12 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0101_alter_family_id_alter_playernotification_notif_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playernotification',
            name='battle_id',
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d9b318ea-53dd-4ac6-ad76-fae0c259a017'), primary_key=True, serialize=False),
        ),
    ]
