# Generated by Django 4.2.7 on 2024-09-13 12:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0104_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ad8708ce-efde-4f7e-ab9f-b263942b1eb8'), primary_key=True, serialize=False),
        ),
    ]
