# Generated by Django 4.2.7 on 2024-09-13 12:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0105_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5f4bbb2b-44b9-4c12-8049-11a850027157'), primary_key=True, serialize=False),
        ),
    ]
