# Generated by Django 4.2.7 on 2024-09-13 12:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0106_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('06111b59-b8f9-46f3-a20e-059a18f52eee'), primary_key=True, serialize=False),
        ),
    ]
