# Generated by Django 4.2.7 on 2024-09-13 19:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0107_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9183b4e4-aab8-4bcf-9453-ffff51ede9b6'), primary_key=True, serialize=False),
        ),
    ]
