# Generated by Django 4.2.7 on 2024-09-13 19:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0108_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cd700b51-0288-4f0d-a0ae-58167c159257'), primary_key=True, serialize=False),
        ),
    ]
