# Generated by Django 4.2.7 on 2024-09-13 19:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0110_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3c2b47e1-1fd6-4bad-92f8-715a4e95f513'), primary_key=True, serialize=False),
        ),
    ]
