# Generated by Django 4.2.7 on 2024-09-15 01:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0112_alter_family_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playernotification',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='playernotification',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('334b787b-808b-4f81-a916-aa62a1d7c020'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playernotification',
            name='notif_type',
            field=models.CharField(max_length=30),
        ),
    ]
