# Generated by Django 4.2.7 on 2024-09-15 01:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0113_playernotification_content_playernotification_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4896e279-c835-48a6-85b2-3e5e728ad2fa'), primary_key=True, serialize=False),
        ),
    ]
