# Generated by Django 4.2.7 on 2024-09-15 01:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0114_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d79c1942-4785-4b8f-bfe5-99642651c01f'), primary_key=True, serialize=False),
        ),
    ]
