# Generated by Django 4.2.7 on 2024-09-16 11:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0115_alter_family_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playernotification',
            name='battle_id',
        ),
        migrations.RemoveField(
            model_name='playernotification',
            name='content',
        ),
        migrations.RemoveField(
            model_name='playernotification',
            name='url',
        ),
        migrations.RemoveField(
            model_name='refreestat',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='refreestat',
            name='rating',
        ),
        migrations.AddField(
            model_name='refreestat',
            name='communication',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='refreestat',
            name='fairness',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='refreestat',
            name='overall',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='refreestat',
            name='timeliness',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('68a13a39-0c07-44b7-9941-a44c30369963'), primary_key=True, serialize=False),
        ),
    ]
