# Generated by Django 4.2.7 on 2024-09-16 19:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0117_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0d8b3cb8-2ce3-4c69-b2f8-61f82584b4c9'), primary_key=True, serialize=False),
        ),
    ]
