# Generated by Django 4.2.7 on 2024-09-16 22:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0118_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c1137526-d7ed-4845-bef0-97b2e5395bb3'), primary_key=True, serialize=False),
        ),
    ]
