# Generated by Django 4.2.7 on 2024-09-16 22:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0119_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3a8aa107-783b-4741-b349-662d94e7c88b'), primary_key=True, serialize=False),
        ),
    ]
