# Generated by Django 4.2.7 on 2024-09-18 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0120_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5a556868-58cd-4db7-a2ee-738b4dfb0eca'), primary_key=True, serialize=False),
        ),
    ]
