# Generated by Django 4.2.7 on 2024-09-18 19:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0122_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1d7f9b85-dcec-4ecd-9722-8e61b77f47a9'), primary_key=True, serialize=False),
        ),
    ]
