# Generated by Django 4.2.7 on 2024-09-19 21:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0123_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c7f316a9-1f33-4f28-9b39-1969086cde8f'), primary_key=True, serialize=False),
        ),
    ]
