# Generated by Django 4.2.7 on 2024-09-19 21:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0124_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('648b3063-bcd5-4c10-aa60-4d4b82f90a78'), primary_key=True, serialize=False),
        ),
    ]
