# Generated by Django 4.2.7 on 2024-09-20 17:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0125_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('75cd7ab4-3d47-4d95-8580-53f8ee485d51'), primary_key=True, serialize=False),
        ),
    ]
