# Generated by Django 4.2.7 on 2024-09-20 17:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0126_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('75ee7af3-a1e0-4683-a673-a2fc2f25cc73'), primary_key=True, serialize=False),
        ),
    ]
