# Generated by Django 4.2.7 on 2024-09-21 00:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0127_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('18cd2cd8-4daf-4982-b448-87d58e71ba30'), primary_key=True, serialize=False),
        ),
    ]
