# Generated by Django 4.2.7 on 2024-09-21 00:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0128_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('82e4b644-2281-4e6e-917c-5a92d13d6979'), primary_key=True, serialize=False),
        ),
    ]
