# Generated by Django 4.2.7 on 2024-09-21 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0129_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8c3da1c8-d46e-4039-9e4f-b8b2eada72a7'), primary_key=True, serialize=False),
        ),
    ]
