# Generated by Django 4.2.7 on 2024-09-21 00:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0131_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cef3cd5e-b3b6-4bb7-a2d3-bf29e01668a8'), primary_key=True, serialize=False),
        ),
    ]
