# Generated by Django 4.2.7 on 2024-09-21 00:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0132_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f08958f1-a178-4e0a-aeda-fa6cfb012fca'), primary_key=True, serialize=False),
        ),
    ]
