# Generated by Django 4.2.7 on 2024-09-21 01:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0133_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('132dbbb6-38db-449e-9004-879c28e99f8d'), primary_key=True, serialize=False),
        ),
    ]
