# Generated by Django 4.2.7 on 2024-09-23 22:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0134_alter_family_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='referall_code',
            field=models.CharField(default='Wx-ref-hra', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e55ad69c-9939-49e8-b236-fa408c520b25'), primary_key=True, serialize=False),
        ),
    ]
