# Generated by Django 4.2.7 on 2024-09-24 12:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0135_player_referall_code_alter_family_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a2c7201d-0789-4d30-b2d9-3fb60f7914a1'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.achievement')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
            options={
                'unique_together': {('player', 'achievement')},
            },
        ),
        migrations.AddField(
            model_name='player',
            name='achievements',
            field=models.ManyToManyField(through='users.PlayerAchievement', to='users.achievement'),
        ),
    ]
