# Generated by Django 4.2.7 on 2024-09-27 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0136_achievement_alter_family_id_playerachievement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d0020e29-8712-4dcc-81cb-53e238e1d63d'), primary_key=True, serialize=False),
        ),
    ]
