# Generated by Django 4.2.7 on 2024-09-27 15:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0138_rename_referall_code_player_referall_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c3772f26-9829-4154-95a3-de39e43abd72'), primary_key=True, serialize=False),
        ),
    ]
