# Generated by Django 4.2.7 on 2024-09-30 11:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0140_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20b5f649-ea56-438a-9ef4-1e9a0fcabe4f'), primary_key=True, serialize=False),
        ),
    ]
