# Generated by Django 4.2.7 on 2024-10-01 07:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0141_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('486803f4-812d-49f0-bda2-795aaa61e639'), primary_key=True, serialize=False),
        ),
    ]
