# Generated by Django 4.2.7 on 2024-10-01 10:32

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0142_alter_family_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2024, 10, 1, 10, 32, 31, 178479, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('53d0da23-8e6b-4d55-b869-94a6f973da70'), primary_key=True, serialize=False),
        ),
    ]
