# Generated by Django 4.2.7 on 2024-10-01 12:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0144_alter_family_id_alter_player_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('43b8f667-3d72-4924-868f-d5672f93e421'), primary_key=True, serialize=False),
        ),
    ]
