# Generated by Django 4.2.7 on 2024-10-02 01:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0145_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('04fac90b-428a-4c69-932b-4c896f594fed'), primary_key=True, serialize=False),
        ),
    ]
