# Generated by Django 4.2.7 on 2024-10-02 12:26

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0146_alter_family_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b57f1b24-9263-4eea-ba9e-1bba27de1d78'), primary_key=True, serialize=False),
        ),
    ]
