# Generated by Django 4.2.7 on 2024-10-02 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0147_family_date_created_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('42ebe80a-0bfd-48e7-a478-cbc71848cf50'), primary_key=True, serialize=False),
        ),
    ]
