# Generated by Django 4.2.7 on 2024-10-06 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0151_player_last_seen_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f9464bf2-7810-43b0-afff-498630296643'), primary_key=True, serialize=False),
        ),
    ]
