# Generated by Django 4.2.7 on 2024-10-07 06:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0152_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('798ea55a-80a9-425c-b540-eb98c4005314'), primary_key=True, serialize=False),
        ),
    ]
