# Generated by Django 4.2.7 on 2024-10-08 12:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0154_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3122be9b-0785-4b20-a7b8-6217d1c37b5d'), primary_key=True, serialize=False),
        ),
    ]
