# Generated by Django 4.2.7 on 2024-10-16 22:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0155_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1b841d19-e7c4-4350-82b9-b44feefeea34'), primary_key=True, serialize=False),
        ),
    ]
