# Generated by Django 4.2.7 on 2024-11-12 04:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0157_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('93f9952b-5cf4-4790-9f04-6f5e3ea7468a'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PasswordRecoveryCode',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
        ),
    ]
