# Generated by Django 4.2.7 on 2024-12-04 17:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0158_alter_family_id_passwordrecoverycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.UUID('076670ee-08ed-4033-8325-52c6cf50350f'), primary_key=True, serialize=False),
        ),
    ]
