# Generated by Django 4.2.7 on 2024-12-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0160_auto_20241205_1034'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='family',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        migrations.RemoveField(
            model_name='family',
            name='id',
        ),
        migrations.AddField(
            model_name='family',
            name='id',
            field=models.BigAutoField(primary_key=True),
        ),
        migrations.AlterField(
            model_name='related_model',
            name='family',
            field=models.ForeignKey(on_delete=models.CASCADE, to='users.family'),
        ),
    ]
