# Generated by Django 4.2.7 on 2024-12-05 10:16

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0161_alter_family_id'),
    ]

    operations = [
        
    ]
