# Generated by Django 4.2.7 on 2024-12-05 14:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FighterTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=30)),
                ('round', models.IntegerField(default=1)),
                ('fighter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.player')),
            ],
        ),
        migrations.CreateModel(
            name='RefreeTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('n_participants', models.IntegerField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('registering', 'registering'), ('not_started', 'not_started'), ('ongoing', 'ongoing'), ('finished', 'finished')], default='registering', max_length=20)),
                ('participation_cost', models.IntegerField(default=500)),
                ('reward', models.IntegerField(default=2000)),
                ('rules', models.TextField(default='rules')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('cover', models.ImageField(default='tournaments/covers/1.png', upload_to=events.models.tournament_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('n_participants', models.IntegerField()),
                ('rules', models.TextField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.player')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentRefreeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.player')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=1)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battles.battle')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.tournament')),
            ],
            options={
                'unique_together': {('battle', 'tournament')},
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='battles',
            field=models.ManyToManyField(through='events.TournamentBattle', to='battles.battle'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='users.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='fighters',
            field=models.ManyToManyField(related_name='fighters', through='events.FighterTournament', to='users.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='refrees',
            field=models.ManyToManyField(through='events.RefreeTournament', to='users.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='users.player'),
        ),
        migrations.CreateModel(
            name='RoundBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battles.battle')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.round')),
            ],
            options={
                'unique_together': {('battle', 'round')},
            },
        ),
        migrations.AddField(
            model_name='round',
            name='battles',
            field=models.ManyToManyField(through='events.RoundBattle', to='battles.battle'),
        ),
        migrations.AddField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.tournament'),
        ),
        migrations.AddField(
            model_name='refreetournament',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.tournament'),
        ),
        migrations.AddField(
            model_name='fightertournament',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='refreetournament',
            unique_together={('refree', 'tournament')},
        ),
        migrations.AlterUniqueTogether(
            name='fightertournament',
            unique_together={('fighter', 'tournament')},
        ),
    ]
