# Generated by Django 4.2.7 on 2024-12-05 19:38

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='cover',
            field=models.ImageField(default='tournaments/covers/4.jpg', upload_to=events.models.tournament_upload_to),
        ),
    ]
