# Generated by Django 4.2.7 on 2024-08-27 23:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0083_alter_family_id'),
        ('events', '0002_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreeTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='event',
        ),
        migrations.AddField(
            model_name='tournament',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='users.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rules',
            field=models.TextField(default='rules'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('not_started', 'not_started'), ('ongoing', 'ongoing'), ('finished', 'finished')], default='not_started', max_length=20),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='refreetournament',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.tournament'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='refrees',
            field=models.ManyToManyField(through='events.RefreeTournament', to='users.player'),
        ),
        migrations.AlterUniqueTogether(
            name='refreetournament',
            unique_together={('refree', 'tournament')},
        ),
    ]
