# Generated by Django 4.2.7 on 2024-08-28 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_alter_family_id'),
        ('events', '0003_refreetournament_remove_tournament_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FighterTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fighter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.tournament')),
            ],
            options={
                'unique_together': {('fighter', 'tournament')},
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='fighters',
            field=models.ManyToManyField(related_name='fighters', through='events.FighterTournament', to='users.player'),
        ),
    ]
