# Generated by Django 4.2.7 on 2024-08-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_tournament_cover_alter_tournament_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightertournament',
            name='character',
            field=models.CharField(default='Ao', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fightertournament',
            name='round',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
