# Generated by Django 4.2.7 on 2024-08-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_fightertournament_character_fightertournament_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fightertournament',
            name='round',
            field=models.IntegerField(default=1),
        ),
    ]
