# Generated by Django 4.2.20 on 2025-07-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_tournament_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='cash_prize',
            field=models.IntegerField(default=30),
        ),
    ]
