# Generated by Django 4.2.7 on 2024-09-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_tournament_date_created_alter_tournament_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
