# Generated by Django 4.2.7 on 2024-09-13 19:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_tournament_cover_alter_tournamentrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='cover',
            field=models.ImageField(default='tournaments/covers/3.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
