# Generated by Django 4.2.7 on 2024-09-14 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0034_alter_roundbattle_unique_together_and_more'),
        ('users', '0112_alter_family_id'),
        ('events', '0016_alter_tournament_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='users.player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='cover',
            field=models.ImageField(default='tournaments/covers/2.jpg', upload_to=''),
        ),
        migrations.CreateModel(
            name='TournamentBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=1)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battles.battle')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.tournament')),
            ],
            options={
                'unique_together': {('battle', 'tournament')},
            },
        ),
        migrations.CreateModel(
            name='RoundBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battles.battle')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.round')),
            ],
            options={
                'unique_together': {('battle', 'round')},
            },
        ),
        migrations.AddField(
            model_name='round',
            name='battles',
            field=models.ManyToManyField(through='events.RoundBattle', to='battles.battle'),
        ),
        migrations.AddField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.tournament'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='battles',
            field=models.ManyToManyField(through='events.TournamentBattle', to='battles.battle'),
        ),
    ]
