# Generated by Django 4.2.7 on 2024-09-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_round_tournament_winner_alter_tournament_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='cover',
            field=models.ImageField(default='tournaments/covers/3.jpg', upload_to=''),
        ),
    ]
