# Generated by Django 4.2.7 on 2024-09-23 22:48

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_alter_tournament_cover_alter_tournament_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='cover',
            field=models.ImageField(default='tournaments/covers/2.jpg', upload_to=events.models.tournament_upload_to),
        ),
    ]
