# Generated by Django 4.2.7 on 2024-10-01 12:01

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_alter_tournament_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='participation_cost',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='tournament',
            name='reward',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='cover',
            field=models.ImageField(default='tournaments/covers/4.jpg', upload_to=events.models.tournament_upload_to),
        ),
    ]
