# Generated by Django 4.2.7 on 2024-10-05 09:00

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_alter_tournament_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='cover',
            field=models.ImageField(default='tournaments/covers/6.jpg', upload_to=events.models.tournament_upload_to),
        ),
    ]
