# Generated by Django 4.2.20 on 2025-07-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderadress',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
