# Generated by Django 4.2.20 on 2025-07-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_orderadress_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
