# Generated by Django 4.2.20 on 2025-09-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_affiliateproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateproduct',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
