# Generated by Django 4.2.7 on 2025-04-28 01:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_comment_id_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='custom_id',
            field=models.CharField(default=core.models.generate_custom_id, max_length=8),
        ),
    ]
