# Generated by Django 4.2.7 on 2025-04-28 06:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='custom_id',
            field=models.CharField(default=core.models.generate_custom_id, max_length=20),
        ),
    ]
