# Generated by Django 4.2.7 on 2024-07-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reacted',
            field=models.BooleanField(default=False),
        ),
    ]
