# Generated by Django 4.2.16 on 2025-05-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
