# Generated by Django 4.2.16 on 2025-05-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_reaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
