# Generated by Django 4.2.7 on 2024-09-15 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0113_playernotification_content_playernotification_url_and_more'),
        ('core', '0007_savedpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.player'),
        ),
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
