# Generated by Django 4.2.16 on 2025-05-23 14:45

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_commentreaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('meme', 'Meme'), ('fact', 'Fun Fact')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('custom_id', models.CharField(default=core.models.generate_custom_id, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContentFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contentpost')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.feed')),
            ],
            options={
                'unique_together': {('content', 'feed')},
            },
        ),
        migrations.AddField(
            model_name='feed',
            name='daily_content',
            field=models.ManyToManyField(through='core.ContentFeed', to='core.contentpost'),
        ),
    ]
