# Generated by Django 4.2.16 on 2025-05-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contentpost_contentfeed_feed_daily_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='img_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
