# Generated by Django 4.2.7 on 2024-09-15 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0114_alter_family_id'),
        ('core', '0008_remove_notification_type_notification_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
