# Generated by Django 4.2.16 on 2025-05-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='clicked',
            field=models.BooleanField(default=False),
        ),
    ]
