# Generated by Django 4.2.16 on 2025-05-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_image_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
