# Generated by Django 4.2.16 on 2025-05-30 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0002_announcement'),
        ('core', '0013_alter_image_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderator.announcement')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.feed')),
            ],
            options={
                'unique_together': {('announcement', 'feed')},
            },
        ),
        migrations.AddField(
            model_name='feed',
            name='announcements',
            field=models.ManyToManyField(through='core.AnnouncementFeed', to='moderator.announcement'),
        ),
    ]
