# Generated by Django 4.2.7 on 2024-10-08 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0154_alter_family_id'),
        ('battles', '0040_battlespectator_battle_spectators'),
        ('core', '0014_alter_savedpost_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattlesFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battles.battle')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battles', models.ManyToManyField(through='core.BattlesFeed', to='battles.battle')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
        ),
        migrations.CreateModel(
            name='PostsFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.feed')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
            ],
            options={
                'unique_together': {('post', 'feed')},
            },
        ),
        migrations.AddField(
            model_name='feed',
            name='posts',
            field=models.ManyToManyField(through='core.PostsFeed', to='core.post'),
        ),
        migrations.AddField(
            model_name='battlesfeed',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.feed'),
        ),
        migrations.AlterUniqueTogether(
            name='battlesfeed',
            unique_together={('battle', 'feed')},
        ),
    ]
