# Generated by Django 4.2.20 on 2025-07-09 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_player_godfather'),
        ('core', '0015_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.contentpost')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.contentcomment')),
            ],
        ),
        migrations.CreateModel(
            name='ContentCommentReactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('👍', 'Like'), ('👎', 'Unlike'), ('😂', 'Laugh'), ('😲', 'Surprise'), ('☹️', 'Unlike')], max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contentcomment')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
            options={
                'unique_together': {('player', 'comment')},
            },
        ),
        migrations.AddField(
            model_name='contentcomment',
            name='reactors',
            field=models.ManyToManyField(related_name='content_comment_reactors', through='core.ContentCommentReactor', to='users.player'),
        ),
    ]
