# Generated by Django 4.2.7 on 2024-10-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0040_battlespectator_battle_spectators'),
        ('core', '0015_battlesfeed_feed_postsfeed_feed_posts_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BattlesFeed',
            new_name='BattleFeed',
        ),
        migrations.RenameModel(
            old_name='PostsFeed',
            new_name='PostFeed',
        ),
    ]
