# Generated by Django 4.2.20 on 2025-07-10 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_player_godfather'),
        ('core', '0016_contentcomment_contentcommentreactor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('👍', 'Like'), ('👎', 'Unlike'), ('😂', 'Laugh'), ('😲', 'Surprise'), ('☹️', 'Unlike')], max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contentpost')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
            options={
                'unique_together': {('player', 'content')},
            },
        ),
        migrations.AddField(
            model_name='contentpost',
            name='reactors',
            field=models.ManyToManyField(related_name='content_reactors', through='core.ContentReactor', to='users.player'),
        ),
    ]
