# Generated by Django 4.2.20 on 2025-08-26 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_storycharacter_custom_id'),
        ('core', '0017_contentreactor_contentpost_reactors'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryCharacterFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.feed')),
                ('story_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.storycharacter')),
            ],
            options={
                'unique_together': {('story_character', 'feed')},
            },
        ),
        migrations.AddField(
            model_name='feed',
            name='story_characters',
            field=models.ManyToManyField(through='core.StoryCharacterFeed', to='story.storycharacter'),
        ),
    ]
