# Generated by Django 4.2.20 on 2025-10-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_storycharacterfeed_feed_story_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('discussion', 'Discussion'), ('others', 'Others'), ('meme', 'Meme'), ('question', 'Question')], default='others', max_length=50),
        ),
    ]
