# Generated by Django 4.2.20 on 2025-10-18 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_player_ip_adress'),
        ('core', '0020_post_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_viewed', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(choices=[('post_page', 'POST_PAGE'), ('feed', 'Feed')], default='feed', max_length=250)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
            ],
            options={
                'unique_together': {('player', 'date_viewed')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='viewers',
            field=models.ManyToManyField(related_name='post_viewer', through='core.PostViewer', to='users.player'),
        ),
    ]
