# Generated by Django 4.2.20 on 2025-12-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_postviewer_post_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcommentreactor',
            name='type',
            field=models.CharField(choices=[('🔥', 'Fire'), ('👍', 'Like'), ('👎', 'Unlike'), ('😂', 'Laugh'), ('😲', 'Surprise'), ('☹️', 'Unlike')], max_length=15),
        ),
        migrations.AlterField(
            model_name='contentreactor',
            name='type',
            field=models.CharField(choices=[('🔥', 'Fire'), ('👍', 'Like'), ('👎', 'Unlike'), ('😂', 'Laugh'), ('😲', 'Surprise'), ('☹️', 'Unlike')], max_length=15),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='type',
            field=models.CharField(choices=[('🔥', 'Fire'), ('👍', 'Like'), ('👎', 'Unlike'), ('😂', 'Laugh'), ('😲', 'Surprise'), ('☹️', 'Unlike')], default='🔥', max_length=15),
        ),
    ]
