# Generated by Django 4.2.20 on 2025-12-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_contentcommentreactor_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('discussion', 'Discussion'), ('divers', 'Divers'), ('meme', 'Meme'), ('question', 'Question')], default='divers', max_length=50),
        ),
    ]
