# Generated by Django 4.2.7 on 2024-07-10 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0035_alter_family_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('friendly', 'friendly'), ('stake', 'stake')], max_length=40)),
                ('character', models.CharField(max_length=50)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.player')),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('not_started', 'not_started'), ('ongoing', 'ongoing'), ('finished', 'finished')], default='not_started', max_length=40)),
                ('flags', models.TextField()),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_ended', models.DateTimeField(blank=True)),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.player')),
                ('opponent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_challenger', to='users.player')),
                ('refree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_refree', to='users.player')),
            ],
        ),
    ]
