# Generated by Django 4.2.7 on 2024-07-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.CharField(choices=[('waiting_refree', 'waiting_refree'), ('not_started', 'not_started'), ('ongoing', 'ongoing'), ('finished', 'finished')], default='waiting_refree', max_length=40),
        ),
    ]
