# Generated by Django 4.2.7 on 2024-12-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
