# Generated by Django 4.2.7 on 2024-07-11 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_family_id'),
        ('battles', '0002_alter_battle_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleAcceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=30)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.player')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='battles.battlerequest')),
            ],
        ),
    ]
