# Generated by Django 4.2.7 on 2024-12-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_alter_battle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
