# Generated by Django 4.2.7 on 2025-04-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0003_alter_battle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='custom_id',
            field=models.CharField(default='<function uuid4 at 0x000001CAF49E8AE0>', max_length=100),
        ),
        migrations.AlterField(
            model_name='battle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
