# Generated by Django 4.2.7 on 2024-07-11 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0003_battleacceptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='battlerequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
