# Generated by Django 4.2.7 on 2025-04-28 06:54

import battles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0003_alter_battle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='custom_id',
            field=models.CharField(default=battles.models.generate_custom_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='battle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
