# Generated by Django 4.2.16 on 2025-05-08 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_family_points'),
        ('battles', '0004_battle_custom_id_alter_battle_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SoloBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_character', models.JSONField()),
                ('bot_character', models.JSONField()),
                ('result', models.CharField(choices=[('win', 'win'), ('lose', 'lose'), ('draw', 'draw')], max_length=20)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_ended', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
        ),
    ]
