# Generated by Django 4.2.7 on 2024-07-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0005_alter_battlerequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='flags',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='type',
            field=models.CharField(choices=[('friendly', 'friendly'), ('stake', 'stake')], max_length=30),
        ),
    ]
