# Generated by Django 4.2.7 on 2025-04-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0005_alter_battle_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='custom_id',
            field=models.CharField(default='<function uuid4 at 0x000001BCDC628AE0>', max_length=100),
        ),
    ]
