# Generated by Django 4.2.16 on 2025-05-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0005_jsontestmodel_solobattle'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsontestmodel',
            name='text_data',
            field=models.TextField(default='[]'),
        ),
    ]
