# Generated by Django 4.2.7 on 2024-07-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0006_alter_battle_flags_alter_battle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='date_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
