# Generated by Django 4.2.16 on 2025-05-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0007_solobattle_finished_alter_solobattle_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solobattle',
            name='log',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
