# Generated by Django 4.2.16 on 2025-05-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0008_alter_solobattle_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='defeat_motif',
            field=models.CharField(blank=True, choices=[('referee decision', 'Referee Decision'), ('latency', 'Latency'), ('abandon', 'Abandon'), ('draw', 'Draw'), ('other', 'Other')], default='referee decision', max_length=50),
        ),
    ]
