# Generated by Django 4.2.16 on 2025-05-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0009_battle_defeat_motif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='defeat_motif',
            field=models.CharField(blank=True, choices=[('referee decision', 'Referee Decision'), ('latency', 'Latency'), ('abandon', 'Abandon'), ('draw', 'Draw'), ('other', 'Other')], default='latency', max_length=50),
        ),
    ]
