# Generated by Django 4.2.7 on 2024-07-12 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_alter_family_id'),
        ('battles', '0009_alter_battle_i_character_alter_battle_o_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreeingProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='battles.battle')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.player')),
            ],
        ),
    ]
