# Generated by Django 4.2.16 on 2025-05-25 22:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0010_alter_battle_defeat_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpad',
            name='date_validated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
