# Generated by Django 4.2.7 on 2024-07-12 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0010_refreeingproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='battles.battlerequest'),
        ),
    ]
