# Generated by Django 4.2.16 on 2025-05-26 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0011_textpad_date_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battles.battlerequest'),
        ),
    ]
