# Generated by Django 4.2.7 on 2024-07-12 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_alter_family_id'),
        ('battles', '0011_battle_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='refree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_refree', to='users.player'),
        ),
    ]
