# Generated by Django 4.2.16 on 2025-05-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0012_alter_battle_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpad',
            name='hidden_action',
            field=models.TextField(blank=True, default=''),
        ),
    ]
