# Generated by Django 4.2.7 on 2025-04-28 01:53

import battles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0012_alter_battle_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='custom_id',
            field=models.CharField(default=battles.models.generate_custom_id, max_length=8),
        ),
    ]
