# Generated by Django 4.2.16 on 2025-05-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0013_textpad_hidden_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
