# Generated by Django 4.2.16 on 2025-05-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0014_battle_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlerequest',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
