# Generated by Django 4.2.7 on 2024-07-13 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_alter_family_id'),
        ('battles', '0014_textpad'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='refreeing_rating',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.CreateModel(
            name='Refree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.player')),
            ],
        ),
    ]
