# Generated by Django 4.2.16 on 2025-05-29 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_player_rp_credits'),
        ('battles', '0015_battlerequest_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextpadReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('👍', 'Like'), ('👎', 'Unlike'), ('😂', 'Laugh'), ('👏', 'Clapping'), ('😱', 'Amazed')], max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
                ('textpad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battles.textpad')),
            ],
            options={
                'unique_together': {('player', 'textpad')},
            },
        ),
        migrations.AddField(
            model_name='textpad',
            name='reactors',
            field=models.ManyToManyField(related_name='reactors', through='battles.TextpadReaction', to='users.player'),
        ),
    ]
