# Generated by Django 4.2.16 on 2025-05-29 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_player_rp_credits'),
        ('battles', '0016_textpadreaction_textpad_reactors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextpadReaction',
            new_name='TextpadReactor',
        ),
    ]
