# Generated by Django 4.2.7 on 2024-07-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0016_battle_can_send_textpad'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpad',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
