# Generated by Django 4.2.7 on 2024-07-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0017_textpad_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='can_send_textpad',
            field=models.BooleanField(default=True),
        ),
    ]
