# Generated by Django 4.2.16 on 2025-05-30 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_player_rp_credits'),
        ('battles', '0017_rename_textpadreaction_textpadreactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextPadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='battles.textpadcomment')),
            ],
        ),
        migrations.CreateModel(
            name='TextPadCommentReactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('👍', 'Like'), ('👎', 'Unlike'), ('😂', 'Laugh'), ('👏', 'Clapping'), ('😱', 'Amazed')], max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battles.textpadcomment')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
            options={
                'unique_together': {('player', 'comment')},
            },
        ),
        migrations.AddField(
            model_name='textpadcomment',
            name='reactors',
            field=models.ManyToManyField(related_name='textpad_comment_reactors', through='battles.TextPadCommentReactor', to='users.player'),
        ),
        migrations.AddField(
            model_name='textpadcomment',
            name='textpad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='battles.textpad'),
        ),
    ]
