# Generated by Django 4.2.16 on 2025-05-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0018_textpadcomment_textpadcommentreactor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
