# Generated by Django 4.2.7 on 2024-07-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0018_alter_battle_can_send_textpad'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpad',
            name='refree_comment',
            field=models.TextField(blank=True),
        ),
    ]
