# Generated by Django 4.2.7 on 2024-07-14 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_alter_family_id'),
        ('battles', '0019_textpad_refree_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_winner', to='users.player'),
        ),
    ]
