# Generated by Django 4.2.16 on 2025-06-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0019_challenge_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='solobattle',
            name='type',
            field=models.CharField(choices=[('training', 'training'), ('adventure', 'adventure'), ('casual', 'casual')], default='casual', max_length=20),
        ),
    ]
