# Generated by Django 4.2.16 on 2025-06-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0020_solobattle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreetest',
            name='situation_a',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refreetest',
            name='situation_b',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
