# Generated by Django 4.2.7 on 2024-07-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0020_battle_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='rules',
            field=models.TextField(blank=True),
        ),
    ]
