# Generated by Django 4.2.16 on 2025-06-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0021_refreetest_situation_a_refreetest_situation_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='viewers',
            field=models.IntegerField(default=0),
        ),
    ]
