# Generated by Django 4.2.7 on 2024-08-02 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0021_battle_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='rules',
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battles.battle')),
            ],
        ),
    ]
