# Generated by Django 4.2.20 on 2025-06-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0022_battle_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.CharField(choices=[('waiting_refree', "En Attente d'arbitrge"), ('not_started', 'Pas commencer'), ('ongoing', 'En Cours'), ('finished', 'Terminer')], default='waiting_refree', max_length=40),
        ),
    ]
