# Generated by Django 4.2.7 on 2024-08-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0022_remove_battle_rules_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='can_send_textpad',
            field=models.BooleanField(default=False),
        ),
    ]
