# Generated by Django 4.2.20 on 2025-06-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0023_alter_battle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='ai_refereeing',
            field=models.BooleanField(default=False),
        ),
    ]
