# Generated by Django 4.2.7 on 2024-08-26 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_tournament'),
        ('battles', '0023_alter_battle_can_send_textpad'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.tournament'),
        ),
    ]
