# Generated by Django 4.2.7 on 2024-08-28 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_tournament_n_participants_tournamentrequest'),
        ('battles', '0024_battle_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='battle',
            name='type',
            field=models.CharField(choices=[('friendly', 'friendly'), ('stake', 'stake'), ('tournament', 'tournament')], max_length=30),
        ),
        migrations.AlterField(
            model_name='battlerequest',
            name='type',
            field=models.CharField(choices=[('friendly', 'friendly'), ('stake', 'stake'), ('tournament', 'tournament')], max_length=40),
        ),
        migrations.CreateModel(
            name='RoundBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battles.battle')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battles.round')),
            ],
            options={
                'unique_together': {('battle', 'round')},
            },
        ),
        migrations.AddField(
            model_name='round',
            name='battles',
            field=models.ManyToManyField(through='battles.RoundBattle', to='battles.battle'),
        ),
        migrations.AddField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.tournament'),
        ),
    ]
