# Generated by Django 4.2.20 on 2025-06-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0024_battle_ai_refereeing'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='ai_rules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
