# Generated by Django 4.2.7 on 2024-08-31 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0025_round_alter_battle_type_alter_battlerequest_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlerequest',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battlerequest',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
