# Generated by Django 4.2.20 on 2025-06-30 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_player_godfather'),
        ('battles', '0025_battle_ai_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='refree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_refree', to='users.player'),
        ),
    ]
