# Generated by Django 4.2.7 on 2024-09-07 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0089_alter_family_id'),
        ('battles', '0026_battlerequest_date_sent_battlerequest_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizScore', models.IntegerField()),
                ('situation1', models.ImageField(upload_to='')),
                ('verdict1', models.TextField()),
                ('situation2', models.ImageField(upload_to='')),
                ('verdict2', models.TextField()),
                ('validated', models.BooleanField()),
                ('comment', models.TextField()),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('expriry_date', models.DateField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
        ),
    ]
