# Generated by Django 4.2.7 on 2024-09-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0027_refreetest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreetest',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='refreetest',
            name='expriry_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='refreetest',
            name='situation1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='refreetest',
            name='situation2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='refreetest',
            name='validated',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='refreetest',
            name='verdict1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='refreetest',
            name='verdict2',
            field=models.TextField(blank=True),
        ),
    ]
