# Generated by Django 4.2.7 on 2024-09-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0028_alter_refreetest_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreetest',
            name='validated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
