# Generated by Django 4.2.7 on 2024-09-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0029_alter_refreetest_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreetest',
            name='expriry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
