# Generated by Django 4.2.7 on 2024-09-09 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0031_alter_refreetest_situation1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleacceptor',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 17, 53, 29, 829712, tzinfo=datetime.timezone.utc)),
        ),
    ]
