# Generated by Django 4.2.7 on 2024-09-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0032_battleacceptor_date_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleacceptor',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
