# Generated by Django 4.2.7 on 2024-09-14 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0033_alter_battleacceptor_date_sent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roundbattle',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='roundbattle',
            name='battle',
        ),
        migrations.RemoveField(
            model_name='roundbattle',
            name='round',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='tournament',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
        migrations.DeleteModel(
            name='RoundBattle',
        ),
    ]
