# Generated by Django 4.2.7 on 2024-09-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0034_alter_roundbattle_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='refreeing_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
