# Generated by Django 4.2.7 on 2024-09-27 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0139_alter_family_id'),
        ('battles', '0037_challenge_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='refreeing_rating',
        ),
        migrations.CreateModel(
            name='RefereeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fairness', models.IntegerField(default=1)),
                ('timeliness', models.IntegerField(default=1)),
                ('communication', models.IntegerField(default=1)),
                ('comment', models.TextField()),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battles.battle')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.player')),
            ],
        ),
    ]
