# Generated by Django 4.2.7 on 2024-10-05 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0150_alter_family_id'),
        ('battles', '0038_remove_battle_refreeing_rating_refereerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleacceptor',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.player'),
        ),
        migrations.AlterField(
            model_name='battleacceptor',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battles.battlerequest'),
        ),
        migrations.AlterField(
            model_name='battlerequest',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.player'),
        ),
        migrations.AlterField(
            model_name='refereerating',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.player'),
        ),
        migrations.AlterField(
            model_name='refree',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.player'),
        ),
        migrations.AlterField(
            model_name='refreeingproposal',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.player'),
        ),
        migrations.AlterField(
            model_name='textpad',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.player'),
        ),
    ]
