# Generated by Django 4.2.7 on 2024-10-06 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0152_alter_family_id'),
        ('battles', '0039_alter_battleacceptor_player_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleSpectator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_viewed', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battles.battle')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.player')),
            ],
            options={
                'unique_together': {('player', 'battle')},
            },
        ),
        migrations.AddField(
            model_name='battle',
            name='spectators',
            field=models.ManyToManyField(related_name='spectators', through='battles.BattleSpectator', to='users.player'),
        ),
    ]
