# Generated by Django 4.2.7 on 2024-10-16 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0040_battlespectator_battle_spectators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='type',
            field=models.CharField(choices=[('friendly', 'friendly'), ('stake', 'stake'), ('tournament', 'tournament'), ('challenge', 'challenge')], max_length=30),
        ),
        migrations.AlterField(
            model_name='battlerequest',
            name='type',
            field=models.CharField(choices=[('friendly', 'friendly'), ('stake', 'stake'), ('tournament', 'tournament'), ('challenge', 'challenge')], max_length=40),
        ),
        migrations.AlterField(
            model_name='refreeingproposal',
            name='battle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battles.battle'),
        ),
    ]
