# Generated by Django 4.2.7 on 2024-07-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='jutsu',
            field=models.TextField(blank=True),
        ),
    ]
