# Generated by Django 4.2.7 on 2025-04-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushsubscription',
            old_name='auth',
            new_name='auth_key',
        ),
        migrations.RenameField(
            model_name='pushsubscription',
            old_name='p256dh',
            new_name='p256dh_key',
        ),
    ]
