# Generated by Django 4.2.20 on 2025-09-15 17:58

from django.db import migrations, models
import django.db.models.deletion
import duels.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0015_player_ip_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('ongoing', 'ongoing'), ('finished', 'finished')], default='pending', max_length=20)),
                ('code', models.CharField(default=duels.models.generate_duel_code, max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True, default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='DuelFighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_viewed', models.DateTimeField(auto_now_add=True)),
                ('character', models.JSONField()),
                ('duel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duels.duel')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.player')),
            ],
            options={
                'unique_together': {('player', 'duel')},
            },
        ),
        migrations.AddField(
            model_name='duel',
            name='fighters',
            field=models.ManyToManyField(related_name='duel_fighters', through='duels.DuelFighter', to='users.player'),
        ),
    ]
