# Generated by Django 4.2.20 on 2025-09-16 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duelfighter',
            name='date_viewed',
        ),
        migrations.CreateModel(
            name='DuelAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.JSONField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('fighter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='duels.duelfighter')),
            ],
        ),
    ]
