# Generated by Django 4.2.20 on 2025-09-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duels', '0002_remove_duelfighter_date_viewed_duelaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='duelaction',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
