# Generated by Django 4.2.20 on 2025-09-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duels', '0003_duelaction_evaluated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duelaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
