# Generated by Django 4.2.20 on 2025-09-18 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_player_ip_adress'),
        ('duels', '0005_duel_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duel',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.player'),
        ),
    ]
