# Generated by Django 4.2.20 on 2025-12-18 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_player_duel_character'),
        ('duels', '0006_alter_duel_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duel_target', to='users.player'),
        ),
    ]
