# Generated by Django 4.2.20 on 2025-08-28 11:19

from django.db import migrations, models
import django.db.models.deletion
import monetization.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_player_ip_adress'),
        ('monetization', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_code', models.CharField(default=monetization.models.generate_login_code, max_length=100, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creators', to='users.player')),
            ],
        ),
        migrations.CreateModel(
            name='CreatorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('youtube', 'YouTube'), ('twitch', 'Twitch'), ('patreon', 'Patreon'), ('other', 'Other')], default='other', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monetization.creator')),
            ],
        ),
    ]
