# Generated by Django 4.2.20 on 2025-09-01 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_player_ip_adress'),
        ('monetization', '0003_creator_creatorlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adress', models.CharField(max_length=100)),
                ('method', models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('crypto', 'Crypto')], default='paypal', max_length=20)),
                ('details', models.TextField(help_text='Provide necessary details like email for PayPal, wallet address for crypto, etc.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
        ),
    ]
