# Generated by Django 4.2.7 on 2024-12-05 14:40

import chat.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_abbr', models.TextField()),
                ('last_message_time_sent', models.DateTimeField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('initiator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.player')),
                ('recipient', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_recipient', to='users.player')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=chat.models.upload_family_message_to)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family', to='users.family')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=chat.models.upload_private_message_to)),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_receiver', to='users.player')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMessageReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_read', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.familymessage')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
            options={
                'unique_together': {('player', 'message')},
            },
        ),
        migrations.AddField(
            model_name='familymessage',
            name='readers',
            field=models.ManyToManyField(related_name='readers', through='chat.FamilyMessageReader', to='users.player'),
        ),
        migrations.AddField(
            model_name='familymessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.player'),
        ),
    ]
