# Generated by Django 4.2.16 on 2025-05-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymessage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
