# Generated by Django 4.2.7 on 2024-06-26 18:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chat_message_chat_initiator_chat_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1410a86e-ce7f-4689-b32a-7a87427feb42'), primary_key=True, serialize=False),
        ),
    ]
