# Generated by Django 4.2.7 on 2024-06-26 19:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message_abbr',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message_time_sent',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('79c083eb-b9c1-414e-b14e-b80a1d410187'), primary_key=True, serialize=False),
        ),
    ]
