# Generated by Django 4.2.7 on 2024-06-28 07:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chat_id_alter_chat_last_message_abbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4396df31-3c55-4693-899c-91ba303b02fc'), primary_key=True, serialize=False),
        ),
    ]
