# Generated by Django 4.2.7 on 2024-06-28 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8573e1ce-612f-4a4c-af28-412ba735f28d'), primary_key=True, serialize=False),
        ),
    ]
