# Generated by Django 4.2.7 on 2024-07-01 13:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8b0cacb4-bb8e-4ba2-8016-2fcc11e95543'), primary_key=True, serialize=False),
        ),
    ]
