# Generated by Django 4.2.7 on 2024-07-04 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_chat_id_familymessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b89ad30c-6049-4b93-a90b-725247dbabb5'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='familymessage',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4be8f931-996a-4f91-97e4-d0d1326fcc26'), primary_key=True, serialize=False),
        ),
    ]
