# Generated by Django 4.2.7 on 2024-09-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
