# Generated by Django 4.2.7 on 2024-09-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
