# Generated by Django 4.2.7 on 2024-09-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_familymessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymessage',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
