# Generated by Django 4.2.7 on 2024-09-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_alter_familymessage_content_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/family/None'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/private/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
