# Generated by Django 4.2.7 on 2024-09-21 00:20

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_alter_familymessage_image_alter_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.upload_family_message_to),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.upload_private_message_to),
        ),
    ]
