# Generated by Django 4.2.7 on 2024-10-05 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0150_alter_family_id'),
        ('chat', '0020_alter_familymessage_image_alter_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymessage',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family', to='users.family'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player'),
        ),
    ]
