# Generated by Django 4.2.7 on 2024-12-04 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0159_familybadge_alter_family_id'),
        ('chat', '0021_alter_familymessage_family_alter_message_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMessageReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_read', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.familymessage')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
            options={
                'unique_together': {('player', 'message')},
            },
        ),
        migrations.AddField(
            model_name='familymessage',
            name='readers',
            field=models.ManyToManyField(related_name='readers', through='chat.FamilyMessageReader', to='users.player'),
        ),
    ]
