# Generated by Django 4.2.20 on 2025-08-10 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('News', 'News'), ('Updates', 'Updates'), ('Tutorials', 'Tutorials')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('leading', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('keywords', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(null=True, upload_to='blog_post_covers/')),
                ('keyword1', models.CharField(blank=True, max_length=100, null=True)),
                ('keyword2', models.CharField(blank=True, max_length=100, null=True)),
                ('keyword3', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, choices=[('fr', 'fr'), ('en', 'en')], default='fr', max_length=100, null=True)),
                ('meta_description', models.TextField(blank=True, default='', null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
