# Generated by Django 4.2.20 on 2026-01-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
