# Generated by Django 4.2.16 on 2025-05-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_keyword1_blogpost_keyword2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='language',
            field=models.CharField(blank=True, choices=[('fr', 'fr'), ('en', 'en')], max_length=100, null=True),
        ),
    ]
