# Generated by Django 4.2.20 on 2026-01-05 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_blogpost_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image_alt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.CreateModel(
            name='BlogPostViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_ip', models.CharField(max_length=45)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='blog_post_viewers', through='blog.BlogPostViewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
