# Generated by Django 4.2.16 on 2025-05-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='language',
            field=models.CharField(blank=True, choices=[('fr', 'fr'), ('en', 'en')], default='fr', max_length=100, null=True),
        ),
    ]
