# Generated by Django 4.2.20 on 2025-08-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='keywords',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
