# Generated by Django 4.2.20 on 2025-08-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
    ]
