# Generated by Django 4.2.20 on 2025-08-02 13:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_storytextpad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storytextpad',
            name='character',
        ),
        migrations.AddField(
            model_name='storytextpad',
            name='challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='story.storychallenge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storytextpad',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
