# Generated by Django 4.2.20 on 2025-08-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_remove_storytextpad_character_storytextpad_challenge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storytextpad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
