# Generated by Django 4.2.20 on 2025-08-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_storypass'),
    ]

    operations = [
        migrations.AddField(
            model_name='storychallenge',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
