# Generated by Django 4.2.20 on 2025-08-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_storychallenge_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='storytextpad',
            name='entry',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
