# Generated by Django 4.2.20 on 2025-08-26 02:17

from django.db import migrations, models
import story.models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_storytextpad_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='storycharacter',
            name='custom_id',
            field=models.CharField(blank=True, default=story.models.generate_custom_id, max_length=100),
        ),
    ]
