# Generated by Django 4.2.20 on 2025-09-03 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_player_ip_adress'),
        ('story', '0008_storycharacter_custom_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoAdsPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
        ),
    ]
