# Generated by Django 4.2.20 on 2025-09-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0009_noadspass'),
    ]

    operations = [
        migrations.AddField(
            model_name='storytextpad',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
