# Generated by Django 4.2.20 on 2025-12-02 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_player_ip_adress'),
        ('story', '0010_storytextpad_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryTextPadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='story.storytextpadcomment')),
            ],
        ),
        migrations.CreateModel(
            name='StoryTextpadReactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('👍', 'Like'), ('👎', 'Unlike'), ('😂', 'Laugh'), ('👏', 'Clapping'), ('😱', 'Amazed')], max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
                ('textpad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.storytextpad')),
            ],
            options={
                'unique_together': {('player', 'textpad')},
            },
        ),
        migrations.CreateModel(
            name='StoryTextPadCommentReactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('👍', 'Like'), ('👎', 'Unlike'), ('😂', 'Laugh'), ('👏', 'Clapping'), ('😱', 'Amazed')], max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.storytextpadcomment')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
            options={
                'unique_together': {('player', 'comment')},
            },
        ),
        migrations.AddField(
            model_name='storytextpadcomment',
            name='reactors',
            field=models.ManyToManyField(related_name='story_textpad_comment_reactors', through='story.StoryTextPadCommentReactor', to='users.player'),
        ),
        migrations.AddField(
            model_name='storytextpadcomment',
            name='textpad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_comments', to='story.storytextpad'),
        ),
        migrations.CreateModel(
            name='StoryReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.storychallenge')),
            ],
            options={
                'unique_together': {('player', 'story')},
            },
        ),
        migrations.AddField(
            model_name='storychallenge',
            name='readers',
            field=models.ManyToManyField(related_name='storyreaders', through='story.StoryReader', to='users.player'),
        ),
        migrations.AddField(
            model_name='storytextpad',
            name='reactors',
            field=models.ManyToManyField(related_name='storyreactors', through='story.StoryTextpadReactor', to='users.player'),
        ),
    ]
