# Generated by Django 4.2.20 on 2025-12-19 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_player_duel_character'),
        ('story', '0011_storytextpadcomment_storytextpadreactor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storytextpad',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.player'),
        ),
    ]
