# Generated by Django 4.2.20 on 2025-12-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_storytextpad_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='storychallenge',
            name='reads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
