# Generated by Django 4.2.16 on 2025-06-04 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='moderator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='moderator.moderator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
