# Generated by Django 4.2.16 on 2025-06-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('item_type', models.CharField(max_length=50)),
                ('effect', models.JSONField()),
                ('rarity', models.CharField(default='common', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CharacaterAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='adventure/characters/appearances')),
            ],
        ),
    ]
