# Generated by Django 4.2.16 on 2025-06-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_adventureitem_characaterappearance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventureplayer',
            name='character_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
