# Generated by Django 4.2.16 on 2025-06-08 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_player_godfather'),
        ('adventure', '0003_alter_adventureplayer_character_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('min_level', models.IntegerField(default=1)),
                ('max_level', models.IntegerField(default=100)),
                ('mission_type', models.CharField(choices=[('defeat', 'Vaincre un ennemi'), ('collect', 'Trouver un objet'), ('explore', 'Explorer une zone'), ('survive', 'Survivre X rounds')], max_length=20)),
                ('target', models.JSONField(blank=True, help_text="Nom de l'ennemi, de l'objet ou zone", max_length=100, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('reward_exp', models.IntegerField(default=50)),
                ('reward_item', models.CharField(blank=True, max_length=100, null=True)),
                ('rarity', models.CharField(choices=[('common', 'Commune'), ('rare', 'Rare'), ('epic', 'Épique')], default='common', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En cours'), ('done', 'Terminée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.missiontemplate')),
            ],
        ),
    ]
