# Generated by Django 4.2.16 on 2025-06-09 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_missiontemplate_playermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('min_level', models.IntegerField(default=1)),
                ('max_level', models.IntegerField(default=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='adventure/maps/zones')),
                ('data', models.JSONField(blank=True, help_text='Zone data in JSON format', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='missiontemplate',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adventure.mapzone'),
        ),
    ]
