# Generated by Django 4.2.16 on 2025-06-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_mapzone_missiontemplate_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapzone',
            old_name='min_level',
            new_name='level_required',
        ),
        migrations.RemoveField(
            model_name='mapzone',
            name='max_level',
        ),
        migrations.AlterField(
            model_name='missiontemplate',
            name='target',
            field=models.CharField(blank=True, help_text="Nom de l'ennemi, de l'objet ou zone", max_length=100, null=True),
        ),
    ]
