# Generated by Django 4.2.16 on 2025-06-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0006_rename_min_level_mapzone_level_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missiontemplate',
            name='reward_item',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
    ]
