# Generated by Django 4.2.16 on 2025-06-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0008_alter_missiontemplate_reward_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missiontemplate',
            name='reward_item',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
    ]
