# Generated by Django 4.2.20 on 2025-06-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0009_alter_missiontemplate_reward_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='missiontemplate',
            name='long_tail_description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
