# Generated by Django 4.2.20 on 2025-07-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0010_missiontemplate_long_tail_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermission',
            name='tries',
            field=models.IntegerField(default=0),
        ),
    ]
