# Generated by Django 4.2.20 on 2025-07-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0011_playermission_tries'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventureplayer',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playermission',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='missiontemplate',
            name='mission_type',
            field=models.CharField(choices=[('defeat', 'Vaincre un ennemi'), ('collect', 'Trouver un objet'), ('explore', 'Explorer une zone'), ('survive', 'Survivre X rounds'), ('dialogue', 'Dialoguer avec un individu')], max_length=20),
        ),
    ]
